# Site settings
title: "Digital Gold Institute: Scarcity in the Digital Realm"
name: Digital Gold Institute
email:
description: Research and development center about scarcity in the digital realm (Bitcoin and crypto-assets) and blockchain technology.
#baseurl: "" # the subpath of your site, e.g. /blog/
url: http://dgi.io
logo: http://dgi.io/img/logo/dgi-logo.png

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: dgi-1

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-126683188-2

include: [_pages]

# Build settings
markdown: kramdown

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
